version: '2'
services:

  php:
    build:
      context: . 
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - ./html/:/var/www/html
    ports:
      - 8001:8001


  db:
    image: mariadb
    restart: always
    volumes:
      - ./mysql/data/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=magento2ee
      - MYSQL_USER=lemp
      - MYSQL_PASSWORD=123456



  pma:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8000:80"
    environment:
      - PMA_HOST=db
